version: '3.8'
services:
    php-app:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php:/var/www/html/
        ports:
            - 8085:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"
        volumes:
            - mysql-datavolume:/var/lib/mysql      
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8086:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db          
volumes:
 mysql-datavolume:      
